# Generated by Django 3.2.6 on 2021-08-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210808_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='params',
            field=models.JSONField(),
        ),
    ]
