# Generated by Django 3.2.6 on 2021-08-08 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_uuid', models.CharField(max_length=50, unique=True)),
                ('requester_params', models.JSONField()),
                ('requester_ip', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
            options={
                'verbose_name': 'TaskResults',
                'verbose_name_plural': 'TaskResults',
            },
        ),
    ]
